pos1-posmode       = single       # (0:single,1:dgps,2:kinematic,3:static,4:movingbase,5:fixed,6:ppp-kine,7:ppp-static)
pos1-frequency     = l1+l2        # (1:l1,2:l1+l2,3:l1+l2+l5,4:l1+l2+l5+l6,5:l1+l2+l5+l6+l7)
pos1-elmask        = 15           # (deg)
pos1-snrmask_r     = off
pos1-snrmask_b     = off
pos1-snrmask_L1    = 0,0,0,0,0,0,0,0,0
pos1-snrmask_L2    = 0,0,0,0,0,0,0,0,0
pos1-snrmask_L5    = 0,0,0,0,0,0,0,0,0
pos1-ionoopt       = brdc         # (0:off,1:brdc,2:sbas,3:dual-freq,4:est-stec,5:ionex-tec,6:qzs-brdc,7:qzs-lex,8:vtec_sf,9:vtec_ef,10:gtec)
pos1-tropopt       = saas         # (0:off,1:saas,2:sbas,3:est-ztd,4:est-ztdgrad)
pos1-posopt1       = off
pos1-posopt2       = off
pos1-posopt3       = off
pos1-posopt4       = off
pos1-posopt5       = off
pos1-exclsats      =              # (prn ... excluded sats)
pos1-navsys        = 45           # (1:gps+2:sbas+4:glo+8:gal+16:qzs+32:bds)
pos2-armode        = off          # (0:off,1:continuous,2:instantaneous,3:fix-and-hold)
pos2-gloarmode     = off          # (0:off,1:on,2:autocal)
pos2-bdsarmode     = off
pos2-arthres       = 3.0
pos2-arthres1      = 0.15
pos2-arthres2      = 0.10
pos2-arthres3      = 0.05
pos2-arthres4      = 0.02
pos2-arlockcnt     = 0
pos2-arelmask      = 0.0
pos2-arminfix      = 10
pos2-elmaskhold    = 0.0
pos2-aroutcnt      = 5
pos2-maxage        = 30.0
pos2-syncsol       = off
pos2-slipthres     = 0.05
pos2-rejthres      = 30.0
pos2-raimode       = off
pos2-raiminf       = 0
pos2-raitermax     = 0
pos2-raweight      = 1.0
pos2-dopthres      = 0.0
pos2-bsighgt       = 0.0
pos2-posopt6       = off
pos2-maxaveep      = 0
pos2-dopthres1     = 0.0
pos2-initrst       = off
pos2-swl1polyt     = off
pos2-swl2polyt     = off
pos2-swaverqd      = 0
pos2-arfilter      = off
pos2-arminfixsats  = 0
out-solformat      = llh          # (0:llh,1:xyz,2:enu,3:nmea)
out-outhead        = off
out-outopt         = off
out-outvel         = off
out-timesys        = gpst         # (0:gpst,1:utc,2:jst,3:tow)
out-timeform       = hms          # (0:tow,1:hms)
out-timendec       = 3
out-degform        = deg
out-fieldsep       = 
out-outsingle      = on
out-maxsolstd      = off
out-height         = ellipsoidal  # (0:ellipsoidal,1:geodetic)
out-geoid          = internal     # (0:internal,1:egm96,2:egm08_2.5,3:egm08_1,4:gsi2000)
out-solstatic      = all          # (0:all,1:single)
out-nmeaintv1      = 0.0
out-nmeaintv2      = 0.0
out-outstat         = off
stats-errratio      = 100.0
stats-errphase      = 0.003
stats-errphaseel    = 0.003
stats-errphasebl    = 0.0
stats-errdoppler    = 10.0
stats-stdbias       = 30.0
stats-stdiono       = 0.03
stats-stdtrop       = 0.3
stats-prnaccelh     = 1.0
stats-prnaccelv     = 0.25
stats-prnbias       = 0.0001
stats-prniono       = 0.001
stats-prntrop       = 0.0001
stats-clkstab       = 5e-12
stats-posopt        = off
stats-erphase       = 0.0
stats-erphaseel     = 0.0
stats-erphasebl     = 0.0
stats-erdoppler     = 0.0
ant1-postype        = rinexhead
ant1-pos1           = 0.0
ant1-pos2           = 0.0
ant1-pos3           = 0.0
ant1-anttype        = 
ant1-antde          = 0.0
ant1-antdn          = 0.0
ant1-antdu          = 0.0
ant2-postype        = single
ant2-pos1           = 0.0
ant2-pos2           = 0.0
ant2-pos3           = 0.0
ant2-anttype        = 
ant2-antde          = 0.0
ant2-antdn          = 0.0
ant2-antdu          = 0.0
misc-timeinterp     = off
misc-sbasatsel      = 0
misc-rtkmode        = off
misc-solstat        = 0
misc-maxaveep       = 0
misc-dgpscorr       = off
file-satantfile     = 
file-rcvantfile     = 
file-staposfile     = 
file-geoidfile      = 
file-dcbfile        = 
file-eopfile        = 
file-blqfile        = 
file-tempdir        = 
file-geexefile      = 
file-solstatfile    = 
file-trace          = 0