pos1-posmode       =kinematic
pos1-frequency     =l1+l2
pos1-elmask        =15
pos1-navsys        =63
pos1-ionoopt       =brdc
pos1-tropopt       =saas
pos2-armode        =fix-and-hold
pos2-gloarmode     =fix-and-hold
pos2-bdsarmode     =on
pos2-arfilter      =on
pos2-arthres       =3
pos2-arlockcnt     =5
pos2-minfixsats    =4
pos2-minholdsats   =5
pos2-mindropsats   =10
pos2-arelmask      =25
pos2-arminfix      =20
pos2-maxage        =30
out-solformat      =llh
out-outhead        =on
out-outopt         =on
out-timesys        =gpst
out-timeform       =hms
out-timendec       =3
out-height         =ellipsoidal
ant1-postype       =rinexhead
ant2-postype       =rinexhead
stats-eratio1      =300
stats-eratio2      =300
stats-errphase     =0.005
stats-stdbias      =30
stats-stdiono      =0.03
stats-stdtrop      =0.3