package org.rtklib.java.otl;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public final class BlqWriter {

    private BlqWriter() {}

    public static void write(String file, String stationName, double lat, double lon,
                              double[][][] blq) throws IOException {
        try (PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter(file)))) {
            pw.printf("$$ OTL coefficients generated by rtklib-otl from FES2004 model%n");
            pw.printf("$$ Station: %s  Lat: %.4f  Lon: %.4f%n", stationName, lat, lon);

            StringBuilder header = new StringBuilder();
            header.append(String.format("%-16s", ""));
            for (String name : BlqConsts.CONSTITUENT_NAMES) {
                header.append(String.format(" %10s", name));
            }
            pw.println(header.toString());

            for (int row = 0; row < 6; row++) {
                StringBuilder sb = new StringBuilder();
                for (int c = 0; c < BlqConsts.NUM_CONSTITUENTS; c++) {
                    int compIdx;
                    int valIdx;
                    if (row < 3) {
                        compIdx = row;
                        valIdx = 0;
                    } else {
                        compIdx = row - 3;
                        valIdx = 1;
                    }
                    sb.append(String.format(" %10.4f", blq[compIdx][c][valIdx]));
                }
                pw.println(sb.toString());
            }
        }
    }
}
