package org.rtklib.java.otl;

import java.io.IOException;

public class BoundaryTest {
    public static void main(String[] args) throws IOException {
        BlqExtractor extractor = new BlqExtractor();

        System.out.println("==========================================================");
        System.out.println("BLQ Boundary and Edge Case Tests");
        System.out.println("==========================================================\n");

        // Test 1: Standard BLQ format output
        System.out.println("TEST 1: Standard BLQ Format Output");
        System.out.println("----------------------------------------------------------");
        testStandardBlqFormat(extractor, "LHASA", 29.65, 91.13);

        // Test 2: High latitude stations
        System.out.println("\nTEST 2: High Latitude Stations");
        System.out.println("----------------------------------------------------------");
        testStation(extractor, "REYKJAVIK", 64.13, -21.90);  // Iceland
        testStation(extractor, "TROMSO", 69.65, 19.00);      // Norway
        testStation(extractor, "LONGYEARBYEN", 78.22, 15.63); // Svalbard

        // Test 3: Polar regions
        System.out.println("\nTEST 3: Polar Regions");
        System.out.println("----------------------------------------------------------");
        testStation(extractor, "NEAR_NORTH_POLE", 89.0, 0.0);
        testStation(extractor, "NEAR_SOUTH_POLE", -89.0, 0.0);
        testStation(extractor, "THULE_GREENLAND", 76.53, -68.68);

        // Test 4: Southern hemisphere
        System.out.println("\nTEST 4: Southern Hemisphere");
        System.out.println("----------------------------------------------------------");
        testStation(extractor, "SYDNEY", -33.87, 151.21);     // Australia
        testStation(extractor, "CAPE_TOWN", -33.92, 18.42);   // South Africa
        testStation(extractor, "BUENOS_AIRES", -34.60, -58.38); // Argentina
        testStation(extractor, "MCMURDO_ANTARCTICA", -77.85, 166.67);

        // Test 5: Coastal stations (near ocean-land boundary)
        System.out.println("\nTEST 5: Coastal Stations");
        System.out.println("----------------------------------------------------------");
        testStation(extractor, "HONOLULU", 21.31, -157.86);   // Hawaii, mid-Pacific
        testStation(extractor, "LISBON", 38.72, -9.14);       // Portugal, Atlantic coast
        testStation(extractor, "TOKYO", 35.68, 139.69);       // Japan, Pacific coast
        testStation(extractor, "SINGAPORE", 1.35, 103.82);    // Near equator, coastal

        // Test 6: Extreme longitudes
        System.out.println("\nTEST 6: Extreme Longitudes (near ±180°)");
        System.out.println("----------------------------------------------------------");
        testStation(extractor, "FIJI", -17.71, 178.06);       // Near +180°
        testStation(extractor, "ALEUTIAN_ISLANDS", 52.0, -175.0); // Near -180°
        testStation(extractor, "NEW_ZEALAND", -41.29, 174.78);

        // Test 7: Equatorial stations
        System.out.println("\nTEST 7: Equatorial Stations");
        System.out.println("----------------------------------------------------------");
        testStation(extractor, "QUITO_ECUADOR", -0.18, -78.47);
        testStation(extractor, "NAIROBI_KENYA", -1.29, 36.82);
        testStation(extractor, "JAKARTA_INDONESIA", -6.21, 106.85);

        // Test 8: Very low elevation coastal (potential numerical issues)
        System.out.println("\nTEST 8: Edge Cases - Small Coordinates");
        System.out.println("----------------------------------------------------------");
        testStation(extractor, "NEAR_EQUATOR_PRIME_MERIDIAN", 0.01, 0.01);
        testStation(extractor, "NEAR_POLE_SMALL_LON", 89.99, 0.01);

        System.out.println("\n==========================================================");
        System.out.println("All boundary tests completed successfully!");
        System.out.println("==========================================================");
    }

    private static void testStandardBlqFormat(BlqExtractor extractor, String name,
                                                double lat, double lon) throws IOException {
        double[][][] blq = extractor.extract(lat, lon);

        System.out.printf("$$ OTL coefficients generated by rtklib-otl from FES2004 model%n");
        System.out.printf("$$ Station: %s  Lat: %.4f  Lon: %.4f%n", name, lat, lon);

        // Header
        System.out.printf("%-16s", "");
        for (String cname : BlqConsts.CONSTITUENT_NAMES) {
            System.out.printf(" %10s", cname);
        }
        System.out.println();

        // 6 rows: 3 amplitude + 3 phase
        for (int row = 0; row < 6; row++) {
            System.out.printf("%-16s", getRowLabel(row));
            for (int c = 0; c < BlqConsts.NUM_CONSTITUENTS; c++) {
                int compIdx = row < 3 ? row : row - 3;
                int valIdx = row < 3 ? 0 : 1;
                System.out.printf(" %10.4f", blq[compIdx][c][valIdx]);
            }
            System.out.println();
        }
    }

    private static void testStation(BlqExtractor extractor, String name,
                                     double lat, double lon) {
        try {
            double[][][] blq = extractor.extract(lat, lon);

            // Check for NaN or Infinity
            boolean hasNaN = false;
            boolean hasInfinity = false;
            double maxAmp = 0;

            for (int comp = 0; comp < 3; comp++) {
                for (int c = 0; c < BlqConsts.NUM_CONSTITUENTS; c++) {
                    double amp = blq[comp][c][0];
                    double phase = blq[comp][c][1];

                    if (Double.isNaN(amp) || Double.isNaN(phase)) {
                        hasNaN = true;
                    }
                    if (Double.isInfinite(amp) || Double.isInfinite(phase)) {
                        hasInfinity = true;
                    }
                    if (amp > maxAmp) {
                        maxAmp = amp;
                    }
                }
            }

            String status = "OK";
            if (hasNaN) status = "FAIL (NaN)";
            else if (hasInfinity) status = "FAIL (Infinity)";

            System.out.printf("  %-25s lat=%7.2f  lon=%8.2f  [%s]  max_amp=%.2f mm%n",
                    name, lat, lon, status, maxAmp);

        } catch (Exception e) {
            System.out.printf("  %-25s lat=%7.2f  lon=%8.2f  [FAIL]  %s%n",
                    name, lat, lon, e.getMessage());
        }
    }

    private static String getRowLabel(int row) {
        switch (row) {
            case 0: return "Rad_Amp(mm)";
            case 1: return "West_Amp(mm)";
            case 2: return "South_Amp(mm)";
            case 3: return "Rad_Phs(deg)";
            case 4: return "West_Phs(deg)";
            case 5: return "South_Phs(deg)";
            default: return "";
        }
    }
}
