pos1-posmode       =static
pos1-frequency     =l1+l2
pos1-soltype       =forward
pos1-elmask        =15
pos1-snrmask_r     =off
pos1-snrmask_b     =off
pos1-dynamics      =off
pos1-tidecorr      =off
pos1-ionoopt       =dual-freq
pos1-tropopt       =saas
pos1-sateph        =brdc
pos1-navsys        =45
pos2-armode        =wlnl
pos2-gloarmode     =off
pos2-bdsarmode     =on
pos2-arfilter      =on
pos2-arthres       =3.0
pos2-arthresmin    =3
pos2-arthresmax    =3
pos2-arelmask      =15
pos2-arminfix      =20
pos2-elmaskhold    =15
pos2-aroutcnt      =20
pos2-maxage        =30
pos2-slipthres     =0.05
pos2-rejionno      =2
pos2-rejcode       =30
pos2-niter         =1
out-solformat      =llh
out-outhead        =on
out-outopt         =on
out-timesys        =gpst
out-timeform       =tow
out-timedec        =3
out-solstatic      =all
ant1-postype       =single
ant2-postype       =rinex
