pos1-posmode       =single
pos1-frequency     =l1
pos1-sateph        =brdc
pos1-navsys        =47
pos1-elmask        =15
pos1-snrmask       =0
pos1-dynamics      =off
pos1-tidecorr      =off
pos1-ionoopt       =brdc
pos1-tropopt       =saas
pos1-aroutcnt      =5
pos1-minlockcnt    =0
pos1-minfixsats    =4
pos1-rcvstds       =off
pos2-bdsarmode     =off
out-solformat      =llh
out-timesys        =gpst
out-degformat      =deg
out-outsingle      =on
